ATTACH DATABASE 'production.db' AS prod;

-- Uspostavlja obavezu poštovanja ograničenja stranih ključeva
PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS INVENTORY_FACT;
DROP TABLE IF EXISTS ORDER_FACT;
DROP TABLE IF EXISTS DIM_TIME;
DROP TABLE IF EXISTS DIM_WAREHOUSE;
DROP TABLE IF EXISTS DIM_PRODUCT;
DROP TABLE IF EXISTS DIM_CUSTOMER;
DROP TABLE IF EXISTS DIM_EMPLOYEE;

CREATE TABLE DIM_EMPLOYEE (
    DIM_EMPLOYEE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PROD_EMPLOYEE_ID INTEGER,
    FULL_NAME TEXT NOT NULL,
    JOB_TITLE TEXT NOT NULL,
    MANAGER_ID INTEGER
);

CREATE TABLE DIM_CUSTOMER (
    DIM_CUSTOMER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PROD_CUSTOMER_ID INTEGER NOT NULL,
    COMPANY_NAME TEXT NOT NULL,
    CREDIT_LIMIT INTEGER NOT NULL,
    REPRESENTATIVE_NAME TEXT NOT NULL,
    REPRESENTATIVE_PHONE TEXT NOT NULL,
    REPRESENTATIVE_EMAIL TEXT NOT NULL
);

CREATE TABLE DIM_PRODUCT (
    DIM_PRODUCT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PROD_PRODUCT_ID INTEGER NOT NULL,
    PRODUCT_NAME TEXT NOT NULL,
    CATEGORY_NAME TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL
);

CREATE TABLE DIM_WAREHOUSE (
    DIM_WAREHOUSE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PROD_WAREHOUSE_ID INTEGER NOT NULL,
    REGION_NAME TEXT NOT NULL,
    COUNTRY_NAME TEXT NOT NULL,
    CITY_NAME TEXT NOT NULL,
    ADDRESS TEXT NOT NULL,
    POSTAL_CODE TEXT NOT NULL
);

CREATE TABLE DIM_TIME (
    ORDER_DATE_ID INTEGER PRIMARY KEY,
    FULL_DATE TEXT NOT NULL,
    YEAR INTEGER NOT NULL,
    QUARTER INTEGER NOT NULL,
    MONTH INTEGER NOT NULL,
    WEEKDAY INTEGER NOT NULL
);

INSERT INTO DIM_EMPLOYEE (PROD_EMPLOYEE_ID, FULL_NAME, JOB_TITLE, MANAGER_ID)
SELECT EMPLOYEE_ID, FIRST_NAME || ' ' || LAST_NAME, JOB_TITLE, MANAGER_ID FROM prod.EMPLOYEES;

INSERT INTO DIM_EMPLOYEE (DIM_EMPLOYEE_ID, PROD_EMPLOYEE_ID, FULL_NAME, JOB_TITLE, MANAGER_ID)
VALUES (0, NULL, 'Unknown', 'Unknown', NULL);

INSERT INTO DIM_CUSTOMER (PROD_CUSTOMER_ID, COMPANY_NAME, CREDIT_LIMIT, REPRESENTATIVE_NAME, REPRESENTATIVE_PHONE, REPRESENTATIVE_EMAIL)
SELECT c.CUSTOMER_ID, c.NAME, c.CREDIT_LIMIT, con.FIRST_NAME || ' ' || con.LAST_NAME, con.PHONE, con.EMAIL
FROM prod.CUSTOMERS c
JOIN prod.CONTACTS con ON c.CUSTOMER_ID = con.CUSTOMER_ID;

INSERT INTO DIM_PRODUCT (PROD_PRODUCT_ID, PRODUCT_NAME, CATEGORY_NAME, DESCRIPTION)
SELECT p.PRODUCT_ID, p.PRODUCT_NAME, pc.CATEGORY_NAME, p.DESCRIPTION
FROM prod.PRODUCTS p
JOIN prod.PRODUCT_CATEGORIES pc ON p.CATEGORY_ID = pc.CATEGORY_ID;

INSERT INTO DIM_WAREHOUSE (PROD_WAREHOUSE_ID, REGION_NAME, COUNTRY_NAME, CITY_NAME, ADDRESS, POSTAL_CODE)
SELECT DISTINCT
    w.WAREHOUSE_ID,
    r.REGION_NAME,
    c.COUNTRY_NAME,
    w.WAREHOUSE_NAME,
    l.ADDRESS,
    l.POSTAL_CODE
FROM prod.WAREHOUSES w
JOIN prod.LOCATIONS l ON w.LOCATION_ID = l.LOCATION_ID
JOIN prod.COUNTRIES c ON l.COUNTRY_ID = c.COUNTRY_ID
JOIN prod.REGIONS r ON c.REGION_ID = r.REGION_ID;

INSERT INTO DIM_TIME (ORDER_DATE_ID, FULL_DATE, YEAR, QUARTER, MONTH, WEEKDAY)
SELECT DISTINCT CAST(strftime('%Y%m%d', ORDER_DATE) AS INTEGER) AS ORDER_DATE_ID, ORDER_DATE, strftime('%Y', ORDER_DATE),
       (strftime('%m', ORDER_DATE) - 1) / 3 + 1, strftime('%m', ORDER_DATE),
       (CASE 
            WHEN strftime('%w', ORDER_DATE) = '0' THEN 7
            ELSE strftime('%w', ORDER_DATE)
        END) AS WEEKDAY
FROM prod.ORDERS;

CREATE TABLE ORDER_FACT (
    DIM_EMPLOYEE_FK INTEGER NOT NULL,
    DIM_CUSTOMER_FK INTEGER NOT NULL,
    DIM_PRODUCT_FK INTEGER NOT NULL,
    ORDER_DATE_FK INTEGER NOT NULL,
    ORDER_ID INTEGER NOT NULL,
    ITEM_ID INTEGER NOT NULL,
    STATUS TEXT NOT NULL,
    QUANTITY INTEGER NOT NULL,
    STANDARD_COST REAL NOT NULL,
    LIST_PRICE REAL NOT NULL,
    PROFIT_MARGIN REAL GENERATED ALWAYS AS (ROUND(LIST_PRICE - STANDARD_COST, 2)) STORED,
    PRIMARY KEY (DIM_EMPLOYEE_FK, DIM_CUSTOMER_FK, DIM_PRODUCT_FK, ORDER_DATE_FK, ORDER_ID, ITEM_ID),
    FOREIGN KEY (DIM_EMPLOYEE_FK) REFERENCES DIM_EMPLOYEE(DIM_EMPLOYEE_ID),
    FOREIGN KEY (DIM_CUSTOMER_FK) REFERENCES DIM_CUSTOMER(DIM_CUSTOMER_ID),
    FOREIGN KEY (DIM_PRODUCT_FK) REFERENCES DIM_PRODUCT(DIM_PRODUCT_ID),
    FOREIGN KEY (ORDER_DATE_FK) REFERENCES DIM_TIME(ORDER_DATE_ID)
);

INSERT INTO ORDER_FACT (DIM_EMPLOYEE_FK, DIM_CUSTOMER_FK, DIM_PRODUCT_FK, ORDER_DATE_FK, ORDER_ID, ITEM_ID, STATUS, QUANTITY, STANDARD_COST, LIST_PRICE)
SELECT COALESCE(de.DIM_EMPLOYEE_ID, 0), dc.DIM_CUSTOMER_ID, dp.DIM_PRODUCT_ID, dt.ORDER_DATE_ID, o.ORDER_ID, oi.ITEM_ID, o.STATUS, oi.QUANTITY, p.STANDARD_COST, p.LIST_PRICE
FROM prod.ORDERS o
JOIN prod.ORDER_ITEMS oi ON o.ORDER_ID = oi.ORDER_ID
JOIN prod.PRODUCTS p ON oi.PRODUCT_ID = p.PRODUCT_ID
LEFT JOIN DIM_EMPLOYEE de ON o.SALESMAN_ID = de.PROD_EMPLOYEE_ID
JOIN DIM_CUSTOMER dc ON o.CUSTOMER_ID = dc.PROD_CUSTOMER_ID
JOIN DIM_PRODUCT dp ON oi.PRODUCT_ID = dp.PROD_PRODUCT_ID
JOIN DIM_TIME dt ON o.ORDER_DATE = dt.FULL_DATE;

CREATE TABLE INVENTORY_FACT (
    ITEM_NUMBER INTEGER PRIMARY KEY AUTOINCREMENT,
    DIM_PRODUCT_FK INTEGER,
    DIM_WAREHOUSE_FK INTEGER,
    QUANTITY INTEGER,
    STANDARD_COST REAL NOT NULL,
    LIST_PRICE REAL NOT NULL,
    PROFIT_MARGIN REAL GENERATED ALWAYS AS (ROUND(LIST_PRICE - STANDARD_COST, 2)) STORED,
    -- PRIMARY KEY (DIM_PRODUCT_FK, DIM_WAREHOUSE_FK),
    FOREIGN KEY (DIM_PRODUCT_FK) REFERENCES DIM_PRODUCT (DIM_PRODUCT_ID),
    FOREIGN KEY (DIM_WAREHOUSE_FK) REFERENCES DIM_WAREHOUSE (DIM_WAREHOUSE_ID)
);

INSERT INTO INVENTORY_FACT (DIM_PRODUCT_FK, DIM_WAREHOUSE_FK, QUANTITY, STANDARD_COST, LIST_PRICE)
SELECT dp.DIM_PRODUCT_ID, dw.DIM_WAREHOUSE_ID, i.QUANTITY, p.STANDARD_COST, p.LIST_PRICE
FROM prod.INVENTORIES i
JOIN prod.PRODUCTS p ON i.PRODUCT_ID = p.PRODUCT_ID
JOIN DIM_PRODUCT dp ON i.PRODUCT_ID = dp.PROD_PRODUCT_ID
JOIN DIM_WAREHOUSE dw ON i.WAREHOUSE_ID = dw.PROD_WAREHOUSE_ID;
